# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Menu',
        ),
    ]
